apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: test2
  namespace: test-jvm-namespace
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: test-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: test2
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: test2-
      labels:
        build.appstudio.openshift.io/application: test-application
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: test2
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      namespace: test-jvm-namespace
    spec:
      params:
      - name: git-url
        value: https://github.com/stuartwdouglas/code-with-quarkus
      - name: output-image
        value: quay.io/sdouglas/release:test-jvm-namespace-test2-$(tt.params.git-revision)
      pipelineRef:
        bundle: quay.io/redhat-appstudio/hacbs-templates-bundle:latest
        name: java-builder
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: test2/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
